###
POST http://localhost:4000/api/users HTTP/1.1
Content-Type: application/json

{
    "Name": "Vladimil",
    "User": "Henry0215",
    "Email":"Vlad@gmail.com",
    "Pass": 123456787
}

###
GET  http://localhost:4000/api/users HTTP/1.1

###
GET  http://localhost:4000/api/users/6404fc75b2f1d2acfba388f5 HTTP/1.1

###
PUT http://localhost:4000/api/users/6404fc75b2f1d2acfba388f5 HTTP/1.1
Content-Type: application/json

{
    "Name": "Henry",
    "User": "Henry0215",
    "Email":"Vladasdas@gmail.com",
    "Pass": 123456787
}

###
DELETE http://localhost:4000/api/users/6404d70eaf51e92b5ccf82e3 HTTP/1.1